"""Render the Markdown demo/research report from a report context dict."""

from __future__ import annotations

from typing import Any, Dict, List


def _table(headers: List[str], rows: List[List[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def build_markdown(ctx: Dict[str, Any]) -> str:
    L: List[str] = []
    L.append(f"# {ctx['title']}")
    L.append("")
    L.append(f"_Generated by **RoboMentor** — material-aware robotics education toolchain._")
    L.append("")

    plan = ctx["plan"]
    L.append("## 1. Project overview")
    L.append("")
    L.append(_table(["Field", "Value"], [
        ["Selected project", ctx["project_name"]],
        ["Selected board", ctx["board_name"]],
        ["Template", plan["template_id"]],
        ["Planner confidence", f"{plan['confidence']:.2f}"],
        ["LLM provider", ctx.get("llm_provider", "heuristic")],
    ]))
    L.append("")
    L.append(f"**Planner reasoning:** {plan['reasoning_summary']}")
    L.append("")

    # Feasibility
    L.append("## 2. Material feasibility")
    L.append("")
    L.append(f"- **Parts used:** {', '.join(plan['used_parts']) or '—'}")
    L.append(f"- **Missing required parts:** {', '.join(plan['missing_required_parts']) or 'none 🎉'}")
    L.append(f"- **Missing optional parts:** {', '.join(plan['missing_optional_parts']) or 'none'}")
    L.append("")

    # BOM
    L.append("## 3. Bill of materials")
    L.append("")
    bom_rows = [[b["component"], b["part_type"], b.get("category", ""), b.get("note", "")]
                for b in ctx["bom"]]
    L.append(_table(["Component", "Part type", "Category", "Note"], bom_rows))
    L.append("")

    # Wiring table
    L.append("## 4. Wiring table")
    L.append("")
    wrows = [[r["from_component"], r["from_pin"], r["to_component"], r["to_pin"], r["net"], r["note"]]
             for r in ctx["wiring_rows"]]
    L.append(_table(["From", "Pin", "To", "Pin", "Net", "Note"], wrows))
    L.append("")

    # Firmware
    L.append("## 5. Firmware")
    L.append("")
    L.append(f"- **Sketch:** `{ctx['firmware_path']}` ({ctx.get('firmware_lines', '?')} lines)")
    if ctx.get("firmware_libraries"):
        L.append(f"- **Libraries:** {', '.join(ctx['firmware_libraries'])}")
    L.append("")
    L.append(ctx.get("firmware_explanation", ""))
    L.append("")

    # Simulation
    sim = ctx["sim"]
    L.append("## 6. Simulation result")
    L.append("")
    L.append(_table(["Field", "Value"], [
        ["Backend", sim.get("backend", "?")],
        ["Available", sim.get("available", False)],
        ["Success", sim.get("success", False)],
        ["Message", sim.get("message", "")],
    ]))
    L.append("")

    # Validation
    val = ctx["validation"]
    L.append("## 7. Validation result")
    L.append("")
    L.append(f"- **Passed:** {'✅ yes' if val['passed'] else '❌ no (see errors)'}")
    L.append(f"- **Errors:** {val['num_errors']}  |  **Warnings:** {val['num_warnings']}  |  **Info:** {val['num_infos']}")
    L.append("")
    if val["issues"]:
        irows = [[i["severity"].upper(), i["code"], i["message"]] for i in val["issues"]]
        L.append(_table(["Severity", "Code", "Message"], irows))
        L.append("")

    # Warnings
    if ctx.get("warnings"):
        L.append("## 8. Warnings")
        L.append("")
        for w in ctx["warnings"]:
            L.append(f"- ⚠️ {w}")
        L.append("")

    # Learning objectives
    L.append("## 9. Educational learning objectives")
    L.append("")
    for o in ctx.get("learning_objectives", []):
        L.append(f"- {o}")
    L.append("")

    # Troubleshooting
    L.append("## 10. Troubleshooting checklist")
    L.append("")
    for t in ctx.get("troubleshooting", []):
        L.append(f"- [ ] {t}")
    L.append("")

    # Artifacts
    L.append("## 11. Generated artifacts")
    L.append("")
    for name, path in ctx.get("artifacts", {}).items():
        L.append(f"- **{name}:** `{path}`")
    L.append("")

    L.append("---")
    L.append("")
    L.append("> Simulation is a learning aid, not a guarantee of real-world behaviour. "
             "Always build with power off and double-check your wiring.")
    return "\n".join(L)
