"""Firmware (sketch) generator.

Generates Arduino-C++ firmware whose pin ``#define``s come **directly** from the
circuit's ``pin_map``, guaranteeing the code-circuit validator can match them.
Every sketch includes:

* named pin constants with wiring comments,
* readable helper functions,
* serial debug logging,
* a tunable motor/output speed where relevant,
* a ``SELF_TEST`` mode toggle,
* beginner-friendly comments.

Boards that run the Arduino core (Uno/Nano/Mega/ESP32/Pico/STM32duino) all use
the Arduino-C++ generator.  An optional MicroPython variant is produced for
ESP32/Pico when requested.
"""

from __future__ import annotations

from typing import Dict, List

from .schemas import Circuit, Firmware, PlannerResult


HEADER = """// ---------------------------------------------------------------------------
// {title}
// Generated by RoboMentor — material-aware robotics education toolchain.
// Board: {board}
//
// This sketch was generated to match the wiring diagram exactly. Every pin
// constant below corresponds to a connection in the circuit diagram.
// Read the comments — they explain WHAT each pin does and WHY.
// ---------------------------------------------------------------------------

// Set SELF_TEST to 1 to cycle outputs once at startup and print a checklist,
// which is handy for confirming your wiring before running the real program.
#define SELF_TEST 0
"""


def _defines(pin_map: Dict[str, str], comments: Dict[str, str]) -> str:
    lines: List[str] = []
    for name, pin in pin_map.items():
        comment = comments.get(name, "")
        suffix = f"  // {comment}" if comment else ""
        # Arduino analog pins (A0..) are valid tokens; numeric pins as ints.
        value = pin if pin.startswith("A") or pin.startswith("GP") or pin.startswith("D") else pin
        lines.append(f"#define {name} {value}{suffix}")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Motor driver code fragments (shared by line follower + obstacle avoider)
# --------------------------------------------------------------------------- #
def _is_tb6612(pin_map: Dict[str, str]) -> bool:
    return "PWMA" in pin_map


def _motor_setup(pin_map: Dict[str, str]) -> str:
    if _is_tb6612(pin_map):
        pins = ["AIN1", "AIN2", "BIN1", "BIN2", "PWMA", "PWMB", "STBY"]
    else:
        pins = ["IN1", "IN2", "IN3", "IN4", "ENA", "ENB"]
    out = "\n".join(f"  pinMode({p}, OUTPUT);" for p in pins if p in pin_map)
    if _is_tb6612(pin_map):
        out += "\n  digitalWrite(STBY, HIGH); // enable the TB6612 driver"
    return out


def _motor_functions(pin_map: Dict[str, str]) -> str:
    if _is_tb6612(pin_map):
        return """
// --- Motor control (TB6612FNG) ------------------------------------------
void leftMotor(int speed, bool forward) {
  digitalWrite(AIN1, forward ? HIGH : LOW);
  digitalWrite(AIN2, forward ? LOW : HIGH);
  analogWrite(PWMA, speed);
}
void rightMotor(int speed, bool forward) {
  digitalWrite(BIN1, forward ? HIGH : LOW);
  digitalWrite(BIN2, forward ? LOW : HIGH);
  analogWrite(PWMB, speed);
}
void stopMotors() { analogWrite(PWMA, 0); analogWrite(PWMB, 0); }
"""
    return """
// --- Motor control (L298N) ----------------------------------------------
void leftMotor(int speed, bool forward) {
  digitalWrite(IN1, forward ? HIGH : LOW);
  digitalWrite(IN2, forward ? LOW : HIGH);
  analogWrite(ENA, speed);   // ENA must be a PWM pin for speed control
}
void rightMotor(int speed, bool forward) {
  digitalWrite(IN3, forward ? HIGH : LOW);
  digitalWrite(IN4, forward ? LOW : HIGH);
  analogWrite(ENB, speed);
}
void stopMotors() { analogWrite(ENA, 0); analogWrite(ENB, 0); }
"""


# --------------------------------------------------------------------------- #
# Per-template generators
# --------------------------------------------------------------------------- #
def _gen_line_follower(circuit: Circuit) -> str:
    pm = circuit.pin_map
    comments = {
        "LEFT_SENSOR_PIN": "Left IR sensor digital OUT (LOW or HIGH over the line)",
        "RIGHT_SENSOR_PIN": "Right IR sensor digital OUT",
        "IN1": "Motor driver IN1 (left motor direction)",
        "IN2": "Motor driver IN2 (left motor direction)",
        "IN3": "Motor driver IN3 (right motor direction)",
        "IN4": "Motor driver IN4 (right motor direction)",
        "ENA": "Motor driver ENA (left motor speed, PWM)",
        "ENB": "Motor driver ENB (right motor speed, PWM)",
        "AIN1": "Left motor direction", "AIN2": "Left motor direction",
        "BIN1": "Right motor direction", "BIN2": "Right motor direction",
        "PWMA": "Left motor speed (PWM)", "PWMB": "Right motor speed (PWM)",
        "STBY": "TB6612 standby (HIGH = enabled)",
    }
    return HEADER.format(title="Line Follower Robot", board=circuit.board.name) + f"""
{_defines(pm, comments)}

// Tune these to your robot. Lower BASE_SPEED if it overshoots the line.
int BASE_SPEED = 150;   // 0..255
int TURN_SPEED = 120;   // speed of the slower wheel while turning

// IR sensors read LOW (0) on a dark line and HIGH (1) on a light floor on
// most modules. If yours is inverted, flip ON_LINE below.
const int ON_LINE = LOW;

{_motor_functions(pm)}

void driveForward() {{ leftMotor(BASE_SPEED, true);  rightMotor(BASE_SPEED, true); }}
void turnLeft()     {{ leftMotor(TURN_SPEED, false); rightMotor(BASE_SPEED, true); }}
void turnRight()    {{ leftMotor(BASE_SPEED, true);  rightMotor(TURN_SPEED, false); }}
void searchLine()   {{ leftMotor(TURN_SPEED, true);  rightMotor(TURN_SPEED, false); }}

void selfTest() {{
  Serial.println(F("[SELF_TEST] Pulsing motors forward for 400ms..."));
  driveForward(); delay(400); stopMotors();
  Serial.println(F("[SELF_TEST] Left sensor: ") );
  Serial.println(digitalRead(LEFT_SENSOR_PIN));
  Serial.print(F("[SELF_TEST] Right sensor: "));
  Serial.println(digitalRead(RIGHT_SENSOR_PIN));
  Serial.println(F("[SELF_TEST] Done. Set SELF_TEST 0 to run normally."));
}}

void setup() {{
  Serial.begin(9600);
  Serial.println(F("RoboMentor line follower starting..."));
  pinMode(LEFT_SENSOR_PIN, INPUT);
  pinMode(RIGHT_SENSOR_PIN, INPUT);
{_motor_setup(pm)}
  stopMotors();
#if SELF_TEST
  selfTest();
#endif
}}

void loop() {{
#if SELF_TEST
  return; // stay idle in self-test mode
#endif
  int left  = digitalRead(LEFT_SENSOR_PIN);
  int right = digitalRead(RIGHT_SENSOR_PIN);

  bool leftOnLine  = (left == ON_LINE);
  bool rightOnLine = (right == ON_LINE);

  if (leftOnLine && rightOnLine) {{
    driveForward();              // both sensors on the line -> go straight
  }} else if (leftOnLine && !rightOnLine) {{
    turnLeft();                  // drifting right -> steer left
  }} else if (!leftOnLine && rightOnLine) {{
    turnRight();                 // drifting left -> steer right
  }} else {{
    searchLine();                // line lost -> rotate to find it again
  }}

  // Serial debug so you can watch the decisions in the Serial Monitor.
  Serial.print(F("L=")); Serial.print(left);
  Serial.print(F(" R=")); Serial.print(right);
  Serial.print(F(" -> "));
  Serial.println(leftOnLine && rightOnLine ? "FWD" :
                 leftOnLine ? "LEFT" : rightOnLine ? "RIGHT" : "SEARCH");
  delay(20);
}}
"""


def _gen_obstacle_avoider(circuit: Circuit) -> str:
    pm = circuit.pin_map
    has_servo = "SERVO_PIN" in pm
    comments = {
        "TRIG_PIN": "HC-SR04 trigger (output pulse)",
        "ECHO_PIN": "HC-SR04 echo (input; 5V! use divider on 3.3V boards)",
        "SERVO_PIN": "Scanning servo signal (PWM)",
    }
    servo_inc = '#include <Servo.h>\nServo scanServo;\n' if has_servo else ""
    servo_setup = "  scanServo.attach(SERVO_PIN);\n  scanServo.write(90);\n" if has_servo else ""
    servo_scan = """
long lookDirection(int angle) {
  scanServo.write(angle);
  delay(300);
  return readDistanceCm();
}
""" if has_servo else ""
    return HEADER.format(title="Obstacle Avoiding Robot", board=circuit.board.name) + f"""
{servo_inc}{_defines(pm, comments)}

int BASE_SPEED = 160;            // forward speed 0..255
const long STOP_DISTANCE_CM = 20; // back up / turn when closer than this

{_motor_functions(pm)}

long readDistanceCm() {{
  digitalWrite(TRIG_PIN, LOW);  delayMicroseconds(2);
  digitalWrite(TRIG_PIN, HIGH); delayMicroseconds(10);
  digitalWrite(TRIG_PIN, LOW);
  long duration = pulseIn(ECHO_PIN, HIGH, 30000UL); // 30ms timeout
  if (duration == 0) return 999;   // nothing in range
  return duration / 58;            // microseconds -> centimetres
}}
{servo_scan}
void driveForward() {{ leftMotor(BASE_SPEED, true);  rightMotor(BASE_SPEED, true); }}
void turnRight()    {{ leftMotor(BASE_SPEED, true);  rightMotor(BASE_SPEED, false); }}
void backUp()       {{ leftMotor(BASE_SPEED, false); rightMotor(BASE_SPEED, false); }}

void selfTest() {{
  Serial.print(F("[SELF_TEST] Distance now: "));
  Serial.print(readDistanceCm()); Serial.println(F(" cm"));
}}

void setup() {{
  Serial.begin(9600);
  Serial.println(F("RoboMentor obstacle avoider starting..."));
  pinMode(TRIG_PIN, OUTPUT);
  pinMode(ECHO_PIN, INPUT);
{_motor_setup(pm)}
{servo_setup}  stopMotors();
#if SELF_TEST
  selfTest();
#endif
}}

void loop() {{
#if SELF_TEST
  selfTest(); delay(500); return;
#endif
  long dist = readDistanceCm();
  Serial.print(F("Distance: ")); Serial.print(dist); Serial.println(F(" cm"));

  if (dist > STOP_DISTANCE_CM) {{
    driveForward();
  }} else {{
    stopMotors(); delay(150);
    backUp();     delay(300);
    turnRight();  delay(400);   // simple avoidance turn
  }}
  delay(40);
}}
"""


def _gen_traffic_light(circuit: Circuit) -> str:
    pm = circuit.pin_map
    has_button = "BUTTON_PIN" in pm
    has_buzzer = "BUZZER_PIN" in pm
    comments = {
        "RED_PIN": "Red LED (through resistor)",
        "YELLOW_PIN": "Yellow LED (through resistor)",
        "GREEN_PIN": "Green LED (through resistor)",
        "BUTTON_PIN": "Pedestrian request button (INPUT_PULLUP)",
        "BUZZER_PIN": "Crossing buzzer",
    }
    button_setup = "  pinMode(BUTTON_PIN, INPUT_PULLUP);\n" if has_button else ""
    buzzer_setup = "  pinMode(BUZZER_PIN, OUTPUT);\n" if has_buzzer else ""
    buzzer_beep = ("  digitalWrite(BUZZER_PIN, HIGH); delay(120); digitalWrite(BUZZER_PIN, LOW);\n"
                   if has_buzzer else "")
    button_check = ("""
  // A pedestrian press shortens the green phase.
  if (digitalRead(BUTTON_PIN) == LOW) {
    Serial.println(F("Pedestrian requested crossing"));
    pedestrianRequest = true;
  }
""" if has_button else "")
    return HEADER.format(title="Smart Traffic Light", board=circuit.board.name) + f"""
{_defines(pm, comments)}

int GREEN_MS  = 4000;
int YELLOW_MS = 1500;
int RED_MS    = 4000;
bool pedestrianRequest = false;

void allOff() {{
  digitalWrite(RED_PIN, LOW);
  digitalWrite(YELLOW_PIN, LOW);
  digitalWrite(GREEN_PIN, LOW);
}}

void setup() {{
  Serial.begin(9600);
  Serial.println(F("RoboMentor traffic light starting..."));
  pinMode(RED_PIN, OUTPUT);
  pinMode(YELLOW_PIN, OUTPUT);
  pinMode(GREEN_PIN, OUTPUT);
{button_setup}{buzzer_setup}  allOff();
#if SELF_TEST
  Serial.println(F("[SELF_TEST] Blinking each LED once."));
  digitalWrite(RED_PIN, HIGH); delay(300); digitalWrite(RED_PIN, LOW);
  digitalWrite(YELLOW_PIN, HIGH); delay(300); digitalWrite(YELLOW_PIN, LOW);
  digitalWrite(GREEN_PIN, HIGH); delay(300); digitalWrite(GREEN_PIN, LOW);
#endif
}}

void loop() {{
  // GREEN
  allOff(); digitalWrite(GREEN_PIN, HIGH);
  Serial.println(F("GREEN"));
{button_check}  delay(pedestrianRequest ? GREEN_MS / 2 : GREEN_MS);
  pedestrianRequest = false;

  // YELLOW
  allOff(); digitalWrite(YELLOW_PIN, HIGH);
  Serial.println(F("YELLOW"));
  delay(YELLOW_MS);

  // RED
  allOff(); digitalWrite(RED_PIN, HIGH);
  Serial.println(F("RED"));
{buzzer_beep}  delay(RED_MS);
}}
"""


def _gen_smart_greenhouse(circuit: Circuit) -> str:
    pm = circuit.pin_map
    has_dht = "DHT_PIN" in pm
    has_ldr = "LDR_PIN" in pm
    has_soil = "SOIL_PIN" in pm
    has_buzzer = "BUZZER_PIN" in pm
    has_led = "STATUS_LED_PIN" in pm
    comments = {
        "DHT_PIN": "DHT22 data line",
        "LDR_PIN": "Light sensor (analog)",
        "SOIL_PIN": "Soil moisture (analog)",
        "BUZZER_PIN": "Alert buzzer",
        "STATUS_LED_PIN": "Status LED",
    }
    dht_inc = '#include "DHT.h"\n#define DHTTYPE DHT22\nDHT dht(DHT_PIN, DHTTYPE);\n' if has_dht else ""
    dht_setup = "  dht.begin();\n" if has_dht else ""
    reads = []
    if has_dht:
        reads.append("""  float t = dht.readTemperature();
  float h = dht.readHumidity();
  Serial.print(F("Temp=")); Serial.print(t); Serial.print(F("C  Hum="));
  Serial.print(h); Serial.println(F("%"));""")
    if has_ldr:
        reads.append("""  int light = analogRead(LDR_PIN);
  Serial.print(F("Light=")); Serial.println(light);""")
    if has_soil:
        reads.append("""  int soil = analogRead(SOIL_PIN);
  Serial.print(F("Soil=")); Serial.println(soil);
  bool dry = soil < 400; // calibrate this threshold for your probe""")
    else:
        reads.append("  bool dry = false;")
    alert = ""
    if has_buzzer or has_led:
        alert = "  if (dry) {\n"
        if has_led:
            alert += "    digitalWrite(STATUS_LED_PIN, HIGH);\n"
        if has_buzzer:
            alert += "    digitalWrite(BUZZER_PIN, HIGH); delay(100); digitalWrite(BUZZER_PIN, LOW);\n"
        alert += "    Serial.println(F(\"ALERT: soil is dry, water the plant!\"));\n"
        alert += "  } else {\n"
        if has_led:
            alert += "    digitalWrite(STATUS_LED_PIN, LOW);\n"
        alert += "  }\n"
    led_setup = "  pinMode(STATUS_LED_PIN, OUTPUT);\n" if has_led else ""
    buzzer_setup = "  pinMode(BUZZER_PIN, OUTPUT);\n" if has_buzzer else ""
    return HEADER.format(title="Smart Greenhouse / Plant Monitor", board=circuit.board.name) + f"""
{dht_inc}{_defines(pm, comments)}

void setup() {{
  Serial.begin(9600);
  Serial.println(F("RoboMentor greenhouse monitor starting..."));
{dht_setup}{led_setup}{buzzer_setup}}}

void loop() {{
{chr(10).join(reads)}
{alert}  delay(2000); // DHT22 must not be read faster than every 2 seconds
}}
"""


_GENERATORS = {
    "arduino_line_follower_v1": _gen_line_follower,
    "obstacle_avoider_v1": _gen_obstacle_avoider,
    "traffic_light_v1": _gen_traffic_light,
    "smart_greenhouse_v1": _gen_smart_greenhouse,
}


def _collect_libraries(circuit: Circuit) -> List[str]:
    from . import part_library

    libs: List[str] = []
    for comp in circuit.components:
        try:
            part = part_library.get_part(comp.part_type)
        except KeyError:
            continue
        for lib in part.libraries:
            if lib not in libs:
                libs.append(lib)
    return libs


def generate_firmware(plan_result: PlannerResult, circuit: Circuit) -> Firmware:
    gen = _GENERATORS.get(plan_result.template_id)
    if gen is None:
        raise KeyError(f"No code generator for template '{plan_result.template_id}'.")
    source = gen(circuit)
    return Firmware(
        language="arduino_cpp",
        filename="sketch.ino",
        source=source,
        libraries=_collect_libraries(circuit),
        pin_constants=dict(circuit.pin_map),
    )
