"""Write (and read back) the on-disk project layout.

The exact folder structure documented in the README and the SKILL is produced
here so the CLI subcommands (``validate``, ``simulate``, ``render``, ``explain``)
can reload a previously generated project.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import board_profiles, circuit_generator, part_library
from .schemas import (
    BoardProfile,
    Circuit,
    ComponentInstance,
    Connection,
    Firmware,
    PlannerResult,
    ValidationReport,
)
from .utils import ensure_dir, read_json, read_text, write_json, write_text


# --------------------------------------------------------------------------- #
# Sub-paths
# --------------------------------------------------------------------------- #
def paths(out_dir: Path) -> Dict[str, Path]:
    out = Path(out_dir)
    return {
        "root": out,
        "firmware": out / "firmware",
        "simulation": out / "simulation",
        "validation": out / "validation",
        "simulation_logs": out / "simulation_logs",
        "renders": out / "renders",
        "report": out / "report",
    }


# --------------------------------------------------------------------------- #
# Writers
# --------------------------------------------------------------------------- #
def write_plan(out_dir: Path, plan: PlannerResult) -> Path:
    return write_json(Path(out_dir) / "project_plan.json", plan.to_dict())


def write_bom(out_dir: Path, circuit: Circuit) -> Path:
    bom: List[Dict[str, Any]] = []
    counts: Dict[str, int] = {}
    for c in circuit.components:
        counts[c.part_type] = counts.get(c.part_type, 0) + 1
    seen: Dict[str, int] = {}
    for c in circuit.components:
        try:
            part = part_library.get_part(c.part_type)
            note = part.explanation
        except KeyError:
            note = ""
        bom.append({
            "component": c.id,
            "label": c.label,
            "part_type": c.part_type,
            "category": c.category,
            "wokwi_id": c.wokwi_id,
            "note": note,
        })
    return write_json(Path(out_dir) / "bill_of_materials.json",
                      {"components": bom, "counts": counts})


def write_circuit_artifacts(out_dir: Path, circuit: Circuit) -> Dict[str, Path]:
    p = paths(out_dir)
    ensure_dir(p["simulation"])
    out: Dict[str, Path] = {}
    out["wiring_table"] = write_text(Path(out_dir) / "wiring_table.csv",
                                     circuit_generator.to_wiring_csv(circuit))
    out["pin_map"] = write_json(Path(out_dir) / "pin_map.json",
                                circuit_generator.to_pin_map(circuit))
    out["diagram"] = write_json(p["simulation"] / "diagram.json",
                                circuit_generator.to_wokwi_diagram(circuit))
    out["wokwi_toml"] = write_text(p["simulation"] / "wokwi.toml", _wokwi_toml(circuit))
    out["circuit_internal"] = write_json(p["simulation"] / "circuit_internal.json",
                                         circuit.to_dict())
    out["wiring_md"] = write_text(Path(out_dir) / "simulation" / "wiring.md",
                                  circuit_generator.to_markdown(circuit))
    return out


def _wokwi_toml(circuit: Circuit) -> str:
    # Wokwi CLI expects a firmware build artifact; RoboMentor generates source
    # only, so we document the assumption clearly and point at relative paths.
    return (
        "# Wokwi project configuration generated by RoboMentor.\n"
        "# NOTE: RoboMentor generates firmware *source*, not a compiled binary.\n"
        "# Compile firmware/sketch.ino (Arduino CLI / PlatformIO) to a .hex/.elf/.uf2\n"
        "# and point 'firmware' below at it before running wokwi-cli.\n"
        "[wokwi]\n"
        "version = 1\n"
        'firmware = "../firmware/build/sketch.hex"   # <-- update after compiling\n'
        'elf = "../firmware/build/sketch.elf"         # <-- update after compiling\n'
        'diagram = "diagram.json"\n'
    )


def write_firmware(out_dir: Path, firmware: Firmware) -> Path:
    p = paths(out_dir)
    ensure_dir(p["firmware"])
    return write_text(p["firmware"] / firmware.filename, firmware.source)


def write_validation(out_dir: Path, report: ValidationReport,
                     extra_md: str = "") -> Dict[str, Path]:
    p = paths(out_dir)
    ensure_dir(p["validation"])
    out: Dict[str, Path] = {}
    out["json"] = write_json(p["validation"] / "validation_report.json", report.to_dict())
    out["md"] = write_text(p["validation"] / "validation_report.md",
                           _validation_md(report) + extra_md)
    return out


def _validation_md(report: ValidationReport) -> str:
    L = ["# Validation report", "",
         f"**Result:** {'PASSED ✅' if report.passed else 'FAILED ❌'}",
         f"- Errors: {len(report.errors)}",
         f"- Warnings: {len(report.warnings)}",
         f"- Info: {len(report.infos)}", ""]
    for title, items in (("Errors", report.errors), ("Warnings", report.warnings),
                         ("Info", report.infos)):
        if not items:
            continue
        L.append(f"## {title}")
        L.append("")
        for i in items:
            L.append(f"- **[{i.code}]** {i.message}" + (f"  \n  _Hint:_ {i.hint}" if i.hint else ""))
        L.append("")
    return "\n".join(L)


def write_simulation_logs(out_dir: Path, sim_result) -> Dict[str, Path]:
    p = paths(out_dir)
    ensure_dir(p["simulation_logs"])
    out: Dict[str, Path] = {}
    out["serial"] = write_text(p["simulation_logs"] / "serial_output.txt",
                               sim_result.serial_output or "(no serial output)\n")
    out["status"] = write_json(p["simulation_logs"] / "simulator_status.json",
                               sim_result.to_dict())
    return out


def write_metrics(out_dir: Path, metrics: Dict[str, Any]) -> Path:
    return write_json(Path(out_dir) / "metrics.json", metrics)


# --------------------------------------------------------------------------- #
# Reader (reload a project for validate/simulate/render/explain subcommands)
# --------------------------------------------------------------------------- #
@dataclass
class LoadedProject:
    plan: PlannerResult
    circuit: Circuit
    firmware: Optional[Firmware]


def load_project(out_dir: Path) -> LoadedProject:
    out = Path(out_dir)
    plan_data = read_json(out / "project_plan.json")
    plan = PlannerResult(**{k: plan_data.get(k) for k in PlannerResult.__dataclass_fields__})

    circ_data = read_json(out / "simulation" / "circuit_internal.json")
    board = BoardProfile(**circ_data["board"])
    components = [ComponentInstance(**c) for c in circ_data["components"]]
    connections = [Connection(**c) for c in circ_data["connections"]]
    circuit = Circuit(board=board, components=components, connections=connections,
                      pin_map=circ_data.get("pin_map", {}))

    firmware = None
    sketch = out / "firmware" / "sketch.ino"
    if sketch.exists():
        firmware = Firmware(language="arduino_cpp", filename="sketch.ino",
                            source=read_text(sketch), pin_constants=circuit.pin_map)
    return LoadedProject(plan=plan, circuit=circuit, firmware=firmware)
